<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSCjJUav\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSCjJUav/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSCjJUav.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSCjJUav\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSCjJUav\App_KernelDevDebugContainer([
    'container.build_hash' => 'SCjJUav',
    'container.build_id' => '9aa1eb1e',
    'container.build_time' => 1677011227,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSCjJUav');
