<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDWfxwFw\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDWfxwFw/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDWfxwFw.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDWfxwFw\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDWfxwFw\App_KernelDevDebugContainer([
    'container.build_hash' => 'DWfxwFw',
    'container.build_id' => '5a0cbd35',
    'container.build_time' => 1677096429,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDWfxwFw');
