<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCXhFp6K\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCXhFp6K/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCXhFp6K.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCXhFp6K\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCXhFp6K\App_KernelDevDebugContainer([
    'container.build_hash' => 'CXhFp6K',
    'container.build_id' => '3830459c',
    'container.build_time' => 1677359541,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCXhFp6K');
